import { EVCategory, VehicleCatalogItem } from '@/types';

export const EV_CATEGORIES: { id: EVCategory; name: string; description: string }[] = [
  {
    id: '4-wheeler',
    name: 'Electric Cars (4-Wheelers)',
    description: 'Electric passenger cars, SUVs, sedans & crossovers',
  },
  {
    id: '2-wheeler',
    name: 'Electric Scooters & Motorcycles',
    description: 'High-speed urban scooters, mopeds & electric bikes',
  },
  {
    id: '3-wheeler',
    name: 'Electric 3-Wheelers',
    description: 'Passenger e-rickshaws, L5 auto-rickshaws & cargo trikes',
  },
  {
    id: 'commercial',
    name: 'Commercial EVs',
    description: 'Light commercial delivery vans, e-trucks & goods carriers',
  },
  {
    id: 'heavy',
    name: 'Buses & Heavy EVs',
    description: 'Electric transit passenger buses & heavy freight trucks',
  },
  {
    id: 'light',
    name: 'E-Cycles & Micro Mobility',
    description: 'Electric bicycles & micro-mobility urban vehicles',
  },
];

export const MASTER_VEHICLE_CATALOG: VehicleCatalogItem[] = [
  // =========================================================================
  // 1. TATA MOTORS
  // =========================================================================
  {
    id: 'cat-tata-nexon-ev-lr',
    category: '4-wheeler',
    manufacturer: 'Tata Motors',
    model: 'Nexon EV Long Range',
    variant: 'Empowered+ Lux 45',
    batteryCapacitykWh: 45.0,
    usableCapacitykWh: 43.2,
    estimatedRangeKm: 345,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 7.2,
    dcMaxPowerKW: 60.0,
    supportedChargingModes: ['AC Fast 7.2kW', 'DC Fast 60kW'],
    typicalEfficiencyWhPerKm: 130,
    motorPowerKW: 106,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },
  {
    id: 'cat-tata-nexon-ev-mr',
    category: '4-wheeler',
    manufacturer: 'Tata Motors',
    model: 'Nexon EV Medium Range',
    variant: 'Fearless+ 30',
    batteryCapacitykWh: 30.0,
    usableCapacitykWh: 28.5,
    estimatedRangeKm: 240,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 7.2,
    dcMaxPowerKW: 50.0,
    supportedChargingModes: ['AC Slow 3.3kW', 'DC Fast 50kW'],
    typicalEfficiencyWhPerKm: 125,
    motorPowerKW: 95,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },
  {
    id: 'cat-tata-curvv-ev-55',
    category: '4-wheeler',
    manufacturer: 'Tata Motors',
    model: 'Curvv EV',
    variant: 'Empowered+ A 55',
    batteryCapacitykWh: 55.0,
    usableCapacitykWh: 52.8,
    estimatedRangeKm: 425,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 7.2,
    dcMaxPowerKW: 70.0,
    supportedChargingModes: ['AC Fast 7.2kW', 'DC Ultra-Fast 70kW'],
    typicalEfficiencyWhPerKm: 128,
    motorPowerKW: 123,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },
  {
    id: 'cat-tata-punch-ev-lr',
    category: '4-wheeler',
    manufacturer: 'Tata Motors',
    model: 'Punch EV Long Range',
    variant: 'Empowered+ S 35',
    batteryCapacitykWh: 35.0,
    usableCapacitykWh: 33.5,
    estimatedRangeKm: 290,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 7.2,
    dcMaxPowerKW: 50.0,
    supportedChargingModes: ['AC Fast 7.2kW', 'DC Fast 50kW'],
    typicalEfficiencyWhPerKm: 120,
    motorPowerKW: 90,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },
  {
    id: 'cat-tata-tiago-ev',
    category: '4-wheeler',
    manufacturer: 'Tata Motors',
    model: 'Tiago EV',
    variant: 'XZ+ Tech Lux 24',
    batteryCapacitykWh: 24.0,
    usableCapacitykWh: 23.0,
    estimatedRangeKm: 220,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 7.2,
    dcMaxPowerKW: 50.0,
    supportedChargingModes: ['AC Slow 3.3kW', 'DC Fast 50kW'],
    typicalEfficiencyWhPerKm: 110,
    motorPowerKW: 55,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },
  {
    id: 'cat-tata-tigor-ev',
    category: '4-wheeler',
    manufacturer: 'Tata Motors',
    model: 'Tigor EV',
    variant: 'XZ+ Lux 26',
    batteryCapacitykWh: 26.0,
    usableCapacitykWh: 24.8,
    estimatedRangeKm: 230,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 3.3,
    dcMaxPowerKW: 25.0,
    supportedChargingModes: ['AC Slow 3.3kW', 'DC Fast 25kW'],
    typicalEfficiencyWhPerKm: 112,
    motorPowerKW: 55,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },

  // =========================================================================
  // 2. MG MOTOR
  // =========================================================================
  {
    id: 'cat-mg-zs-ev',
    category: '4-wheeler',
    manufacturer: 'MG Motor',
    model: 'ZS EV',
    variant: 'Exclusive Pro 50.3kWh',
    batteryCapacitykWh: 50.3,
    usableCapacitykWh: 48.0,
    estimatedRangeKm: 360,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 7.4,
    dcMaxPowerKW: 60.0,
    supportedChargingModes: ['AC Fast 7.4kW', 'DC Fast 60kW'],
    typicalEfficiencyWhPerKm: 138,
    motorPowerKW: 130,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },
  {
    id: 'cat-mg-windsor-ev',
    category: '4-wheeler',
    manufacturer: 'MG Motor',
    model: 'Windsor EV',
    variant: 'Essence 38kWh',
    batteryCapacitykWh: 38.0,
    usableCapacitykWh: 36.5,
    estimatedRangeKm: 280,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 7.4,
    dcMaxPowerKW: 45.0,
    supportedChargingModes: ['AC Fast 7.4kW', 'DC Fast 45kW'],
    typicalEfficiencyWhPerKm: 132,
    motorPowerKW: 100,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },
  {
    id: 'cat-mg-comet-ev',
    category: '4-wheeler',
    manufacturer: 'MG Motor',
    model: 'Comet EV',
    variant: 'Exclusive FC 17.3kWh',
    batteryCapacitykWh: 17.3,
    usableCapacitykWh: 16.5,
    estimatedRangeKm: 160,
    connectorTypes: ['Type2'],
    acMaxPowerKW: 7.4,
    dcMaxPowerKW: 0,
    supportedChargingModes: ['AC Fast 7.4kW'],
    typicalEfficiencyWhPerKm: 105,
    motorPowerKW: 31,
    seatingCapacity: 4,
    dataSource: 'VERIFIED',
    active: true,
  },
  {
    id: 'cat-mg-cyberster',
    category: '4-wheeler',
    manufacturer: 'MG Motor',
    model: 'Cyberster',
    variant: 'GT AWD 77kWh',
    batteryCapacitykWh: 77.0,
    usableCapacitykWh: 74.0,
    estimatedRangeKm: 450,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 11.0,
    dcMaxPowerKW: 144.0,
    supportedChargingModes: ['AC 11kW', 'DC Ultra-Fast 144kW'],
    typicalEfficiencyWhPerKm: 165,
    motorPowerKW: 400,
    seatingCapacity: 2,
    dataSource: 'VERIFIED',
    active: true,
  },

  // =========================================================================
  // 3. MAHINDRA
  // =========================================================================
  {
    id: 'cat-mahindra-xuv400',
    category: '4-wheeler',
    manufacturer: 'Mahindra',
    model: 'XUV400 EV',
    variant: 'EL Pro 39.4kWh',
    batteryCapacitykWh: 39.4,
    usableCapacitykWh: 37.8,
    estimatedRangeKm: 295,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 7.2,
    dcMaxPowerKW: 50.0,
    supportedChargingModes: ['AC Fast 7.2kW', 'DC Fast 50kW'],
    typicalEfficiencyWhPerKm: 135,
    motorPowerKW: 110,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },
  {
    id: 'cat-mahindra-be6e',
    category: '4-wheeler',
    manufacturer: 'Mahindra',
    model: 'BE 6e',
    variant: 'Pack 1 79kWh',
    batteryCapacitykWh: 79.0,
    usableCapacitykWh: 76.0,
    estimatedRangeKm: 520,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 11.0,
    dcMaxPowerKW: 175.0,
    supportedChargingModes: ['AC 11kW', 'DC Ultra-Fast 175kW'],
    typicalEfficiencyWhPerKm: 148,
    motorPowerKW: 210,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },
  {
    id: 'cat-mahindra-xev9e',
    category: '4-wheeler',
    manufacturer: 'Mahindra',
    model: 'XEV 9e',
    variant: 'Pack 1 79kWh',
    batteryCapacitykWh: 79.0,
    usableCapacitykWh: 76.0,
    estimatedRangeKm: 500,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 11.0,
    dcMaxPowerKW: 175.0,
    supportedChargingModes: ['AC 11kW', 'DC Ultra-Fast 175kW'],
    typicalEfficiencyWhPerKm: 152,
    motorPowerKW: 210,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },

  // =========================================================================
  // 4. HYUNDAI
  // =========================================================================
  {
    id: 'cat-hyundai-ioniq-5',
    category: '4-wheeler',
    manufacturer: 'Hyundai',
    model: 'Ioniq 5',
    variant: 'RWD 72.6kWh',
    batteryCapacitykWh: 72.6,
    usableCapacitykWh: 70.0,
    estimatedRangeKm: 480,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 11.0,
    dcMaxPowerKW: 150.0,
    supportedChargingModes: ['AC 11kW', 'DC Ultra-Fast 150kW'],
    typicalEfficiencyWhPerKm: 145,
    motorPowerKW: 160,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },
  {
    id: 'cat-hyundai-creta-ev',
    category: '4-wheeler',
    manufacturer: 'Hyundai',
    model: 'Creta Electric',
    variant: 'Long Range 45kWh',
    batteryCapacitykWh: 45.0,
    usableCapacitykWh: 43.0,
    estimatedRangeKm: 350,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 11.0,
    dcMaxPowerKW: 80.0,
    supportedChargingModes: ['AC 11kW', 'DC Fast 80kW'],
    typicalEfficiencyWhPerKm: 128,
    motorPowerKW: 102,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },
  {
    id: 'cat-hyundai-kona-ev',
    category: '4-wheeler',
    manufacturer: 'Hyundai',
    model: 'Kona Electric',
    variant: 'Premium 39.2kWh',
    batteryCapacitykWh: 39.2,
    usableCapacitykWh: 38.0,
    estimatedRangeKm: 300,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 7.2,
    dcMaxPowerKW: 50.0,
    supportedChargingModes: ['AC 7.2kW', 'DC Fast 50kW'],
    typicalEfficiencyWhPerKm: 130,
    motorPowerKW: 100,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },

  // =========================================================================
  // 5. KIA
  // =========================================================================
  {
    id: 'cat-kia-ev6',
    category: '4-wheeler',
    manufacturer: 'Kia',
    model: 'EV6',
    variant: 'GT-Line AWD 77.4kWh',
    batteryCapacitykWh: 77.4,
    usableCapacitykWh: 74.0,
    estimatedRangeKm: 500,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 11.0,
    dcMaxPowerKW: 240.0,
    supportedChargingModes: ['AC 11kW', 'DC Ultra-Fast 240kW'],
    typicalEfficiencyWhPerKm: 150,
    motorPowerKW: 239,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },
  {
    id: 'cat-kia-ev9',
    category: '4-wheeler',
    manufacturer: 'Kia',
    model: 'EV9',
    variant: 'GT-Line 99.8kWh',
    batteryCapacitykWh: 99.8,
    usableCapacitykWh: 96.0,
    estimatedRangeKm: 540,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 11.0,
    dcMaxPowerKW: 210.0,
    supportedChargingModes: ['AC 11kW', 'DC Ultra-Fast 210kW'],
    typicalEfficiencyWhPerKm: 180,
    motorPowerKW: 283,
    seatingCapacity: 7,
    dataSource: 'VERIFIED',
    active: true,
  },

  // =========================================================================
  // 6. BYD
  // =========================================================================
  {
    id: 'cat-byd-atto3',
    category: '4-wheeler',
    manufacturer: 'BYD',
    model: 'Atto 3',
    variant: 'Superior 60.48kWh',
    batteryCapacitykWh: 60.48,
    usableCapacitykWh: 58.0,
    estimatedRangeKm: 410,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 7.4,
    dcMaxPowerKW: 80.0,
    supportedChargingModes: ['AC 7.4kW', 'DC Fast 80kW'],
    typicalEfficiencyWhPerKm: 142,
    motorPowerKW: 150,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },
  {
    id: 'cat-byd-seal',
    category: '4-wheeler',
    manufacturer: 'BYD',
    model: 'Seal',
    variant: 'Performance AWD 82.5kWh',
    batteryCapacitykWh: 82.5,
    usableCapacitykWh: 80.0,
    estimatedRangeKm: 520,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 11.0,
    dcMaxPowerKW: 150.0,
    supportedChargingModes: ['AC 11kW', 'DC Ultra-Fast 150kW'],
    typicalEfficiencyWhPerKm: 155,
    motorPowerKW: 390,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },
  {
    id: 'cat-byd-e6',
    category: '4-wheeler',
    manufacturer: 'BYD',
    model: 'e6 MPV',
    variant: 'GLX 71.7kWh',
    batteryCapacitykWh: 71.7,
    usableCapacitykWh: 69.0,
    estimatedRangeKm: 415,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 6.6,
    dcMaxPowerKW: 60.0,
    supportedChargingModes: ['AC 6.6kW', 'DC Fast 60kW'],
    typicalEfficiencyWhPerKm: 165,
    motorPowerKW: 70,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },

  // =========================================================================
  // 7. BMW
  // =========================================================================
  {
    id: 'cat-bmw-i4',
    category: '4-wheeler',
    manufacturer: 'BMW',
    model: 'i4',
    variant: 'eDrive40 83.9kWh',
    batteryCapacitykWh: 83.9,
    usableCapacitykWh: 80.7,
    estimatedRangeKm: 520,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 11.0,
    dcMaxPowerKW: 205.0,
    supportedChargingModes: ['AC 11kW', 'DC Ultra-Fast 205kW'],
    typicalEfficiencyWhPerKm: 158,
    motorPowerKW: 250,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },
  {
    id: 'cat-bmw-ix',
    category: '4-wheeler',
    manufacturer: 'BMW',
    model: 'iX',
    variant: 'xDrive50 111.5kWh',
    batteryCapacitykWh: 111.5,
    usableCapacitykWh: 105.2,
    estimatedRangeKm: 570,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 11.0,
    dcMaxPowerKW: 195.0,
    supportedChargingModes: ['AC 11kW', 'DC Ultra-Fast 195kW'],
    typicalEfficiencyWhPerKm: 190,
    motorPowerKW: 385,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },
  {
    id: 'cat-bmw-i7',
    category: '4-wheeler',
    manufacturer: 'BMW',
    model: 'i7',
    variant: 'xDrive60 101.7kWh',
    batteryCapacitykWh: 101.7,
    usableCapacitykWh: 98.0,
    estimatedRangeKm: 550,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 22.0,
    dcMaxPowerKW: 195.0,
    supportedChargingModes: ['AC 22kW', 'DC Ultra-Fast 195kW'],
    typicalEfficiencyWhPerKm: 185,
    motorPowerKW: 400,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },

  // =========================================================================
  // 8. MERCEDES-BENZ
  // =========================================================================
  {
    id: 'cat-mercedes-eqa',
    category: '4-wheeler',
    manufacturer: 'Mercedes-Benz',
    model: 'EQA',
    variant: '250+ 70.5kWh',
    batteryCapacitykWh: 70.5,
    usableCapacitykWh: 66.5,
    estimatedRangeKm: 440,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 11.0,
    dcMaxPowerKW: 100.0,
    supportedChargingModes: ['AC 11kW', 'DC Fast 100kW'],
    typicalEfficiencyWhPerKm: 155,
    motorPowerKW: 140,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },
  {
    id: 'cat-mercedes-eqs',
    category: '4-wheeler',
    manufacturer: 'Mercedes-Benz',
    model: 'EQS',
    variant: '580 4MATIC 107.8kWh',
    batteryCapacitykWh: 107.8,
    usableCapacitykWh: 107.8,
    estimatedRangeKm: 670,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 22.0,
    dcMaxPowerKW: 200.0,
    supportedChargingModes: ['AC 22kW', 'DC Ultra-Fast 200kW'],
    typicalEfficiencyWhPerKm: 165,
    motorPowerKW: 385,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },

  // =========================================================================
  // 9. AUDI
  // =========================================================================
  {
    id: 'cat-audi-q8-etron',
    category: '4-wheeler',
    manufacturer: 'Audi',
    model: 'Q8 e-tron',
    variant: '55 quattro 114kWh',
    batteryCapacitykWh: 114.0,
    usableCapacitykWh: 106.0,
    estimatedRangeKm: 500,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 22.0,
    dcMaxPowerKW: 170.0,
    supportedChargingModes: ['AC 22kW', 'DC Ultra-Fast 170kW'],
    typicalEfficiencyWhPerKm: 210,
    motorPowerKW: 300,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },

  // =========================================================================
  // 10. VOLVO
  // =========================================================================
  {
    id: 'cat-volvo-xc40-recharge',
    category: '4-wheeler',
    manufacturer: 'Volvo',
    model: 'XC40 Recharge',
    variant: 'Ultimate Twin 78kWh',
    batteryCapacitykWh: 78.0,
    usableCapacitykWh: 75.0,
    estimatedRangeKm: 420,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 11.0,
    dcMaxPowerKW: 150.0,
    supportedChargingModes: ['AC 11kW', 'DC Ultra-Fast 150kW'],
    typicalEfficiencyWhPerKm: 178,
    motorPowerKW: 300,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },
  {
    id: 'cat-volvo-c40-recharge',
    category: '4-wheeler',
    manufacturer: 'Volvo',
    model: 'C40 Recharge',
    variant: 'Ultimate Twin 78kWh',
    batteryCapacitykWh: 78.0,
    usableCapacitykWh: 75.0,
    estimatedRangeKm: 440,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 11.0,
    dcMaxPowerKW: 150.0,
    supportedChargingModes: ['AC 11kW', 'DC Ultra-Fast 150kW'],
    typicalEfficiencyWhPerKm: 170,
    motorPowerKW: 300,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },

  // =========================================================================
  // 11. PORSCHE & JAGUAR & CITROËN
  // =========================================================================
  {
    id: 'cat-porsche-taycan',
    category: '4-wheeler',
    manufacturer: 'Porsche',
    model: 'Taycan',
    variant: '4S Performance Plus 93.4kWh',
    batteryCapacitykWh: 93.4,
    usableCapacitykWh: 83.7,
    estimatedRangeKm: 450,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 22.0,
    dcMaxPowerKW: 270.0,
    supportedChargingModes: ['AC 22kW', 'DC Ultra-Fast 270kW'],
    typicalEfficiencyWhPerKm: 195,
    motorPowerKW: 390,
    seatingCapacity: 4,
    dataSource: 'VERIFIED',
    active: true,
  },
  {
    id: 'cat-citroen-ec3',
    category: '4-wheeler',
    manufacturer: 'Citroën',
    model: 'ë-C3',
    variant: 'Shine 29.2kWh',
    batteryCapacitykWh: 29.2,
    usableCapacitykWh: 28.0,
    estimatedRangeKm: 245,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 3.3,
    dcMaxPowerKW: 30.0,
    supportedChargingModes: ['AC Slow 3.3kW', 'DC Fast 30kW'],
    typicalEfficiencyWhPerKm: 115,
    motorPowerKW: 42,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },
  {
    id: 'cat-maruti-e-vitara',
    category: '4-wheeler',
    manufacturer: 'Maruti Suzuki',
    model: 'e VITARA',
    variant: 'Dual Motor AWD 61kWh',
    batteryCapacitykWh: 61.0,
    usableCapacitykWh: 58.5,
    estimatedRangeKm: 430,
    connectorTypes: ['CCS2', 'Type2'],
    acMaxPowerKW: 11.0,
    dcMaxPowerKW: 120.0,
    supportedChargingModes: ['AC 11kW', 'DC Ultra-Fast 120kW'],
    typicalEfficiencyWhPerKm: 135,
    motorPowerKW: 135,
    seatingCapacity: 5,
    dataSource: 'VERIFIED',
    active: true,
  },

  // =========================================================================
  // 12. ELECTRIC SCOOTERS & MOTORCYCLES (2-WHEELERS)
  // =========================================================================
  {
    id: 'cat-ather-450x',
    category: '2-wheeler',
    manufacturer: 'Ather Energy',
    model: '450X Gen 3',
    variant: '3.7kWh Pack',
    batteryCapacitykWh: 3.7,
    usableCapacitykWh: 3.4,
    estimatedRangeKm: 110,
    connectorTypes: ['Type2', 'Ather Grid Prop'],
    acMaxPowerKW: 0.8,
    dcMaxPowerKW: 3.3,
    supportedChargingModes: ['Ather Grid Fast', 'Home Portable 800W'],
    typicalEfficiencyWhPerKm: 31,
    motorPowerKW: 6.4,
    seatingCapacity: 2,
    dataSource: 'VERIFIED',
    active: true,
  },
  {
    id: 'cat-ola-s1-pro',
    category: '2-wheeler',
    manufacturer: 'Ola Electric',
    model: 'S1 Pro Gen 2',
    variant: '4kWh Pack',
    batteryCapacitykWh: 4.0,
    usableCapacitykWh: 3.8,
    estimatedRangeKm: 140,
    connectorTypes: ['Type2', 'Ola Hypercharger'],
    acMaxPowerKW: 0.75,
    dcMaxPowerKW: 3.0,
    supportedChargingModes: ['Ola Hypercharger', 'Home Portable 750W'],
    typicalEfficiencyWhPerKm: 28,
    motorPowerKW: 11.0,
    seatingCapacity: 2,
    dataSource: 'VERIFIED',
    active: true,
  },
  {
    id: 'cat-tvs-iqube',
    category: '2-wheeler',
    manufacturer: 'TVS',
    model: 'iQube ST',
    variant: '5.1kWh Pack',
    batteryCapacitykWh: 5.1,
    usableCapacitykWh: 4.8,
    estimatedRangeKm: 150,
    connectorTypes: ['Type2'],
    acMaxPowerKW: 0.95,
    dcMaxPowerKW: 1.5,
    supportedChargingModes: ['AC Home 950W'],
    typicalEfficiencyWhPerKm: 32,
    motorPowerKW: 4.4,
    seatingCapacity: 2,
    dataSource: 'VERIFIED',
    active: true,
  },
  {
    id: 'cat-bajaj-chetak',
    category: '2-wheeler',
    manufacturer: 'Bajaj',
    model: 'Chetak Premium',
    variant: '3.2kWh Pack',
    batteryCapacitykWh: 3.2,
    usableCapacitykWh: 3.0,
    estimatedRangeKm: 108,
    connectorTypes: ['Type2'],
    acMaxPowerKW: 0.8,
    dcMaxPowerKW: 1.0,
    supportedChargingModes: ['AC Home 800W'],
    typicalEfficiencyWhPerKm: 30,
    motorPowerKW: 4.2,
    seatingCapacity: 2,
    dataSource: 'VERIFIED',
    active: true,
  },
  {
    id: 'cat-hero-vida-v1',
    category: '2-wheeler',
    manufacturer: 'Hero MotoCorp',
    model: 'Vida V1 Pro',
    variant: '3.94kWh Removable Pack',
    batteryCapacitykWh: 3.94,
    usableCapacitykWh: 3.7,
    estimatedRangeKm: 110,
    connectorTypes: ['Type2'],
    acMaxPowerKW: 0.8,
    dcMaxPowerKW: 2.5,
    supportedChargingModes: ['Ather/Vida Grid Fast', 'Home Portable'],
    typicalEfficiencyWhPerKm: 33,
    motorPowerKW: 6.0,
    seatingCapacity: 2,
    dataSource: 'VERIFIED',
    active: true,
  },
];
