const fs = require('fs');

async function auditHyderabadSrinagar() {
  console.log('=== VOLTCONNECT 2.0 — HYDERABAD -> SRINAGAR SEGMENT AUDIT ===\n');

  // Fetch OSRM Route for Hyderabad -> Srinagar
  const waypoints = [
    { name: 'Hyderabad (Gachibowli)', latitude: 17.435, longitude: 78.385 },
    { name: 'Srinagar (Kashmir)', latitude: 34.0837, longitude: 74.7973 }
  ];

  const coordsString = waypoints.map(w => `${w.longitude.toFixed(6)},${w.latitude.toFixed(6)}`).join(';');
  const url = `https://router.project-osrm.org/route/v1/driving/${coordsString}?overview=full&geometries=geojson&steps=true`;

  const res = await fetch(url);
  const data = await res.json();
  const route = data.routes[0];
  const totalRoadDistanceKm = Math.round((route.distance / 1000) * 10) / 10;
  const geometry = route.geometry.coordinates.map(c => [c[1], c[0]]);

  console.log('Route Distance:', totalRoadDistanceKm, 'km');
  console.log('Geometry Points:', geometry.length);

  // BMW iX Specs
  const bmwIX = {
    id: 'veh-bmw-ix',
    manufacturer: 'BMW',
    model: 'iX xDrive50',
    batteryCapacitykWh: 111.5,
    usableCapacitykWh: 105.2,
    estimatedRangeKm: 612,
    currentBatteryPercent: 100,
    connectorTypes: ['CCS2', 'Type2'],
  };

  const safetyReservePercent = 15;
  const nominalRangeKm = bmwIX.estimatedRangeKm; // 612 km
  const startingSOCPercent = 100;

  // Effective Usable Planning Range = practicalRange * (1 - safetyReserve)
  const effectivePlanningRangeKm = Math.max(120, Math.round(nominalRangeKm * (1 - safetyReservePercent / 100))); // 520 km
  const leg1UsableRangeKm = Math.max(60, Math.round(effectivePlanningRangeKm * (startingSOCPercent / 100))); // 520 km

  console.log('\n--- VEHICLE SPECS ---');
  console.log('Vehicle:', bmwIX.manufacturer, bmwIX.model);
  console.log('Battery Capacity:', bmwIX.batteryCapacitykWh, 'kWh');
  console.log('Usable Capacity:', bmwIX.usableCapacitykWh, 'kWh');
  console.log('Nominal Range:', nominalRangeKm, 'km');
  console.log('Starting SOC:', startingSOCPercent, '%');
  console.log('Safety Reserve:', safetyReservePercent, '%');
  console.log('Effective Safe Planning Range (per leg after 15% reserve):', effectivePlanningRangeKm, 'km');
  console.log('Leg 1 Usable Range (100% SOC):', leg1UsableRangeKm, 'km');

  // Let's load the station pipeline to inspect recommended stops
  // Load stationsSeed or simulate the 4 recommended stops generated by tripPlanningEngine
  // In tripPlanningEngine for Hyderabad -> Srinagar (2,306.8 km):
  // Let's calculate the exact candidates and recommended stops
}

auditHyderabadSrinagar().catch(console.error);
